// server/shared/constants.js
module.exports = {
  MONEY_START: 100,
  MONEY_WRONG_PENALTY: 100,
  MONEY_PICKUP_AMOUNT: 100,
  MONEY_PICKUPS_PER_CORRECT: 1,
  MONEY_PICKUP_RADIUS: 18,
  MONEY_PICKUP_TTL_MS: 25000,
  MONEY_ROAD_SPAWN_TRIES: 40,
};
